version: '3.8'
services:
  app:
    image: sps-django:latest
    restart: always
    build:
      context: ./application
      network: host
      dockerfile: Dockerfile
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    ports:
      - "8000:8000"
    networks:
      - app-network

  db:
    image: 'postgres'
    hostname: db
    restart: always
    # user: postgres
    # command: postgres -c stats_temp_directory=/tmp # -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_PROJECTS_DATABASE}'" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 80s
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "5m"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_PROJECTS_DATABASE}
    ports:
      - '5433:5432'
    volumes:
      - ${POSTGRES_VOLUME_HOST_PATH}/postgres_data:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./etc/postgresql/12/main:/etc/postgresql TODO: may be useful to import conf files
    networks:
      - app-network

networks:
  app-network:
      driver: bridge