version: "3.8"
services:
    app:
        image: "sps-django:${BRANCH}"
        restart: always
        build:
            context: ./application
            network: host
            dockerfile: Dockerfile
        logging:
            driver: json-file
            options:
                max-file: "10"
                max-size: "5m"
        ports:
            - "8000:8000"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
